In [ ]:
import pandas as pd 

results_1872_2026 = pd.read_csv("../data/raw/results_1872_2026.csv")

print(results_1872_2026.shape)
results_1872_2026.head(2)

(49287, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False

In [9]:
results_1872_2026.tail(2)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

# Seperate data into played games (score already determined) and 2026 WC fixtures

In [13]:
historical_matches = results_1872_2026[results_1872_2026['home_score'].notna()].copy()
wc_fixtures = results_1872_2026[results_1872_2026['home_score'].isna()].copy()

historical_matches.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [14]:
wc_fixtures.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49215,2026-06-11,Mexico,South Africa,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49216,2026-06-11,South Korea,Czech Republic,NaN,NaN,FIFA World Cup,Zapopan,Mexico,True
49217,2026-06-12,Canada,Bosnia and Herzegovina,NaN,NaN,FIFA World Cup,Toronto,Canada,False
49218,2026-06-12,United States,Paraguay,NaN,NaN,FIFA World Cup,Inglewood,United States,False
49219,2026-06-13,Qatar,Switzerland,NaN,NaN,FIFA World Cup,Santa Clara,United States,True

In [17]:
# save the data into a seperate csv file
historical_matches.to_csv("../data/processed/historical_matches.csv")
wc_fixtures.to_csv("../data/processed/wc_fixtures.csv")

print(f"Historical Matches: {len(historical_matches)}")
print(f"2026 WC Fixtures: {len(wc_fixtures)}")

Historical Matches: 49215
2026 WC Fixtures: 72